<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Drive.Plugin.SDK/Drive.Plugin.SDK.csproj" /></ItemGroup>
</Project>
